services:
  db:
    container_name: postgres
    image: postgres:16.3
    restart: always
    ports:
    - 5432:5432
    volumes:
    - data:/var/lib/postgresql/data
    env_file:
      - docker.env

  pg-admin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    ports: 
    - 5050:5050
    env_file:
      - docker.env

volumes:
  data: 